/*
 Blinky
 @omzn  2020/10/20
 */
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include "inc/hw_i2c.h"
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_types.h"
#include "inc/hw_qei.h"
#include "inc/hw_timer.h"
#include "driverlib/rom.h"
#include "driverlib/gpio.h"
#include "driverlib/i2c.h"
#include "driverlib/systick.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/uart.h"
#include "driverlib/pwm.h"
#include "driverlib/timer.h"
#include "driverlib/qei.h"
#include "utils/uartstdio.h"
#include "utils/uartstdio.c" //strong-arm method

#include "periphConf.h" //generated by PinMux

#include "my_util.h"

//*****************************************************************************
//
// This function sets up UART0 to be used for a console to display information
// as the example is running.
//
//*****************************************************************************
void initConsole(void) {
	// Enable GPIO port A which is used for UART0 pins.
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	// Configure the pin muxing for UART0 functions on port A0 and A1.
	// This step is not necessary if your part does not support pin muxing.
	GPIOPinConfigure(GPIO_PA0_U0RX);
	GPIOPinConfigure(GPIO_PA1_U0TX);
	// Enable UART0 so that we can configure the clock.
	SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
	// Use the internal 16MHz oscillator as the UART clock source.
	UARTClockSourceSet(UART0_BASE, UART_CLOCK_PIOSC);
	// Select the alternate (UART) function for these pins.
	GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);
	// Initialize the UART for console I/O.
	UARTStdioConfig(0, 9600, 16000000);
}

void initInterruptPins(void) {
	// You can write your own code here.
	//GPIOIntDisable(GPIO_PORTF_BASE, INT_ALL_BUTTONS);
	GPIOIntClear(GPIO_PORTF_BASE, INT_ALL_BUTTONS);

	GPIOIntRegister(GPIO_PORTF_BASE, SW1PinIntHandler);

	GPIOIntTypeSet(GPIO_PORTF_BASE, INT_ALL_BUTTONS, GPIO_FALLING_EDGE);

	//GPIOIntEnable(GPIO_PORTF_BASE, INT_ALL_BUTTONS);
}

void initPWMLEDCtl(void) {
	SysCtlPeripheralEnable(SYSCTL_PERIPH_PWM1);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

	GPIOPinConfigure(GPIO_PF2_M1PWM6);
	GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_2);

	GPIOPinConfigure(GPIO_PF3_M1PWM7);
	GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_3);

	GPIOPinConfigure(GPIO_PF1_M1PWM5);
	GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_1);


	PWMGenConfigure(PWM1_BASE, PWM_GEN_2,
	PWM_GEN_MODE_UP_DOWN | PWM_GEN_MODE_NO_SYNC);
	PWMGenConfigure(PWM1_BASE, PWM_GEN_3,
	PWM_GEN_MODE_UP_DOWN | PWM_GEN_MODE_NO_SYNC);

	PWMGenPeriodSet(PWM1_BASE, PWM_GEN_2, 10000); //PWMClock=1000000
	PWMGenPeriodSet(PWM1_BASE, PWM_GEN_3, 10000);

	//PWMPulseWidthSet(PWM1_BASE, PWM_OUT_5, 500);
	//PWMPulseWidthSet(PWM1_BASE, PWM_OUT_6, 500);
	//PWMPulseWidthSet(PWM1_BASE, PWM_OUT_7, 500);

	PWMOutputState(PWM1_BASE, PWM_OUT_5_BIT, true);
	PWMOutputState(PWM1_BASE, PWM_OUT_6_BIT, true);
	PWMOutputState(PWM1_BASE, PWM_OUT_7_BIT, true);

	PWMGenEnable(PWM1_BASE, PWM_GEN_2);
	PWMGenEnable(PWM1_BASE, PWM_GEN_3);

}

void setPulseWidth(int32_t r, int32_t g, int32_t b){
    PWMPulseWidthSet(PWM1_BASE, PWM_OUT_5, r);
    PWMPulseWidthSet(PWM1_BASE, PWM_OUT_7, g);
    PWMPulseWidthSet(PWM1_BASE, PWM_OUT_6, b);
}

//*****************************************************************************
// Event handers
//*****************************************************************************

void SysTickIntHandler(void) {
	static uint32_t tick_blue = 0;
	static uint32_t tick_green = 0;
	static uint32_t tick_red = 0;

	int r = 20;
	int tick_max = 1000 / r;

	static uint8_t phase = 0;
	static uint8_t suppress = 3;

	switch(phase){
	case 0:
		if(tick_blue <= tick_max / 3){
			tick_blue++;
			tick_red++;
			tick_green++;
		} else {
			phase = 1;
			suppress = 1;
		}
		break;
	case 1:
		if(tick_red > 0){
			tick_red--;
			tick_green--;
			tick_blue += 2;
		} else {
			phase = 2;
		}
		break;
	case 2:
		if(tick_red <= tick_max){
			tick_blue--;
			tick_red++;
		} else {
			phase = 3;
		}
		break;
	case 3:
		if(tick_green <= tick_max){
			tick_red--;
			tick_green++;
		} else {
			phase = 4;
		}
		break;
	case 4:
		if(tick_green > 0){
			tick_green--;
		} else {
			phase = 0;
			suppress = 0;
		}
		break;
	}

	setPulseWidth(tick_red * r, tick_green * r, tick_blue * r);
}

int main(void) {
	// Set the clocking to run directly from the crystal.
	ROM_SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
	SYSCTL_XTAL_16MHZ);
	// Set up ports hardware (see periphConf.c)
	PortFunctionInit();

	// Remove GPIO interrupt initialization
	// initInterruptPins();

	// Initialize console
	initConsole();
	UARTprintf("Hello, world!\n");

	GPIOIntEnable(GPIO_PORTF_BASE,INT_ALL_BUTTONS);
	// GPIOPinWrite(GPIO_PORTF_BASE, LED_ALL, led_color);

	initPWMLEDCtl();

	SysTickPeriodSet(SysCtlClockGet() / SYSTICKS_PER_SEC);
	SysTickEnable();
	SysTickIntRegister(SysTickIntHandler);
	SysTickIntEnable();

	while (1);
}
